name: "MotoDeployDevelop"

on:
  push:
    branches: ["Develop"]
  pull_request:
    branches: ["Develop"]

jobs:
  deploy-code-to-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_NAME }}
          password: ${{ secrets.DEV_SSH_PASSWORD }}
          port: ${{ secrets.DEV_SSH_PORT }}

          script: |
            cd ${{ secrets.DEV_PROJECT_DIR }};
            git checkout Main;
            git checkout -- .
            git -c credential.helper='!f() { echo "username=${{secrets.GIT_AUTH_NAME}}"; echo "password=${{secrets.GIT_AUTH_TOKEN}}"; }; f' pull
            docker service update --force moto_front_moto_node
