name: "MotoDeployDevelop"

on:
  push:
    branches: ["Develop"]
  pull_request:
    branches: ["Develop"]

jobs:
  build-and-deploy-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./docker/nginx/
          file: ./docker/nginx/dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/moto-front-nginx:develop
          build-args: |
            GIT_TOKEN=${{ secrets.GIT_AUTH_TOKEN}}

  build-deploy-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Build web app
        run: npm run build
      - name: create ssh key
        run: touch $HOME/key.pem && chmod 600 $HOME/key.pem && echo "${{secrets.SSH_PRIVATE_KEY}}" > $HOME/key.pem && chmod 600 $HOME/key.pem
      - name: Deploy to server
        if: success()
        run: cd www && rsync --omit-dir-times -e "ssh -p ${{secrets.SSH_PORT}} -i $HOME/key.pem -o StrictHostKeyChecking=no" --archive --compress --delete . ${{secrets.SSH_USER}}@${{secrets.HOST}}:${{secrets.PROJECT_FOLDER}}
